require('options')
require('keymaps')
require('misc')
require('plugins')

require('colorscheme')
require('lsp')
require('plugins.noice')
require('plugins.lualine')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.auto-save')
